#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar  8 20:37:36 2021

@author: Josey
"""

[['R' 'B' 'R' 'B' 'R']
 ['B' 'R' 'B' 'R' 'B']
 ['R' 'B' 'R' 'B' 'R']
 ['B' 'R' 'B' 'R' 'B']
 ['R' 'B' 'R' 'B' 'R']]